import Layout from "@/components/layout";
import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import { useEffect } from "react";

//main css
import { PaylioProvider } from "@/context/context";
import "@/styles/globals.scss";
import PersonalTab from "@/components/loginTwo/PersonalTab";
import { AuthProvider } from "@/context/AuthContext";
import { useRouter } from "next/router";
import SnackbarProvider from "@/components/SnackbarProvider";


export default function App({ Component, pageProps }) {
  // useEffect(() => {
  //   require("bootstrap/dist/js/bootstrap.bundle.min.js");
  // }, []);

  

  // const isLogin = false;
  if (Component?.getLayout) {
    return Component?.getLayout(
      <>
        <Head>
          <title>
            Jain Wallet
          </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="\webfonts\faviconnew.ico" />
        </Head>
        <SnackbarProvider>
        <PaylioProvider>
        <AuthProvider>
       
        <Component {...pageProps} />
         
        </AuthProvider>
      </PaylioProvider>
        </SnackbarProvider>
        
      </>
    );
  }

  return (
    <>
      <Head>
        <title>
          Jain Wallet
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\webfonts\favicon.ico" />
      </Head>
      <SnackbarProvider>
      <PaylioProvider>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </PaylioProvider>
      </SnackbarProvider>
    </>
  );
}
